### ISSUE TITLE
Scripts should inherit from Sandbox.ModAPI.Ingame.MyGridProgram

### ISSUE THREAD

**Issue by maragnus** [gilgame/SEWorkbench#12]
It would appear that scripts created in the editor inherit from System.Object and do not provide access to the members such as Me, Echo, ElaspedTime, Storage and GridTerminalSystem.  GridTerminalSystem is provided via static but this is not a correct representation of the ingame script.

**Comment by gilgame** [comment]
Fixed. Will be included in the next build. Thanks.
