### ISSUE TITLE
Old code is used when compiling collection

### ISSUE THREAD

**Issue by SaberSnail** [gilgame/SEWorkbench#14]
Create a collection with two files.
File A:

```
void Main(string argument)
{
    Foo();
}
```

File B:

```
void Foo()
{
}
```

Open both files. Select File A. Run the script. This will succeed.
Change `Foo` to `Foo2` in both files. Select File A. Run the script. This will fail because the combined script contains the original version of File B rather than the updated version.

**Comment by SaberSnail** [comment]
Oof, my apologies. I just realized that my recreation was using a technically unsupported feature. I manually edited the project file so that a file was contained both in the library and in a collection. This lets me modify the code once and have it be included in multiple collections. I still have to manually build each collection, but it was basically working after implementing PR #15. I completely get it if you wanted to pursue alternate solutions, and there may be a cleaner way for this to work correctly.

**Comment by gilgame** [comment]
It's alright. After reviewing the merge again, I realized that it's just going to pull the same exact ProjectItemViewModel object by using GetItemByPath(). I'm going to leave this issue open for now because the next feature I want to tackle is inclusions such as what you're attempting to do.

**Comment by SaberSnail** [comment]
Yeah, makes sense. I think you are pretty close on having inclusions work as it is.

**Comment by gilgame** [comment]
Beta 6: Workbench will now always use code from disk when compiling. Inclusions have been added.
