### ISSUE TITLE
SEWorkbench Has Stopped Working

### ISSUE THREAD

**Issue by 304bl** [gilgame/SEWorkbench#16]
Hello guys, awesome IDE u made here, u doing a great job for the SE' people.
Unfortunatly for me , i have this issue.I hope u can help me. 

i have no idea why SEWorkbench crash immediatly .
Any fix i could try ?

**Comment by gilgame** [comment]
Give the [latest release](https://github.com/gilgame/SEWorkbench/releases) a try. If you're still having issues, try copying over the contents of "C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Bin" Just the files inside, not the folders and see if it still crashes.

**Comment by 304bl** [comment]
the last release fix it !
thanks a lot !

**Comment by MariuszPL55** [comment]
Not working on my computer ;c
