### ISSUE TITLE
Failed to Copy Sandbox

### ISSUE THREAD

**Issue by Aneutronic** [gilgame/SEWorkbench#24]
I tried upacking the zipped folder to my desktop, and running SE Workbench, but it said it could not locate space engineers, and had me locate it manually. I did, and it then threw this exception:
![se workbench error message](https://cloud.githubusercontent.com/assets/22585092/22383784/3a07878a-e499-11e6-8e81-207e8fc102ca.PNG)

     After that, it spat out this, which it told me to post to GitHub:
(System.MissingMethodException) Method not found: 'Void VRage.FileSystem.MyFileSystem.Init(System.String, System.String, System.String)'.

   at Gilgame.SEWorkbench.Interop.Engine.SetPaths()
   at Gilgame.SEWorkbench.Interop.Engine.Initialize()
   at Gilgame.SEWorkbench.Program.Main(String[] args)

     I made sure neither steam nor space engineers were running, and I unpacked the SE Workbench folder to my desktop where there were no file access permission issues, like there can be in the "Program Files" folder. No such luck. I also tried copying the entire Bin64 folder out of the space engineers folder and into the SE Workbench directory as a subdirectory, but it still did not automatically find it. I tried to direct it to the copied Bin64 folder, but it still gave the same error messages.

     Finally, I tried manually copying the files in the Bin64 directory out of steam and into the SE Workbench directory directly, and it still spat out error messages and refused to work.

     By the way, when I unpacked the file on my desktop, I renamed it from "SEWorkbench" to SE Workbench" (with a space).

     I hope this information helps get to the root of the problem!

**Comment by gilgame** [comment]
Duplicate https://github.com/gilgame/SEWorkbench/issues/22
